/* Coloured Triangles */

/*
A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

The different possibilities are:
> Colour here:        G G        B G        R G        B R
> Becomes colour:      G          R          B          G

With a bigger example:
R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G

You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would the given RRGBRGBB you should return G.

The input string will only contain the uppercase letters R, G, B and there will be at least one letter so you do not have to test for invalid input.
If you are only given one colour as the input, return that colour.
*/

/* 
P - One argument as a string representing the colors (RGB) in the first row of a triangle. Will contain at least one letter.
R - String representing the final color that would appear in the bottom row.
E - 
triangle("GB")          // "R"
triangle("RRR")         // "R"
triangle("RGBG")        // "B"
P - 
function triangle(row) {
    // While row.length > 1
    // Create an empty string.
    // Iterate through row and compare [index, index + 1] values.
    // Add missing RGB value to the created string. ie: pair of "GG" returns "G", pair of "BG" returns "R".
    // Set string to row and repeat until one character remains.
}
*/

function triangle(row) {
    while (row.length > 1) {
        let newRow = "";
        for (let i = 0; i < row.length - 1; i++) {
            switch (row[i] + row[i + 1]) {
                case "BG":
                case "GB": 
                    newRow += "R";
                    break;
                case "RG":
                case "GR":
                    newRow += "B";
                    break;
                case "RB":
                case "BR": 
                    newRow += "G";
                    break;
                default: 
                    newRow += row[i];
                    break;
            }
        }

        row = newRow;
    }

    return row;
}

// Alternate solution: 
// function triangle(row) {
//     let reduced = row.length > 1 ? '' : row;
//     for (let i = 0; i < row.length - 1; i += 1) {
//       reduced += row[i] == row[i+1] ? row[i] : 'RGB'.replace(row[i], '').replace(row[i+1], '');
//     }

//     return reduced.length > 1 ? triangle(reduced) : reduced;
// }

// Test: 
// console.log(triangle("GB"))
// console.log(triangle("RRR"))
// console.log(triangle("RGBG"))
// console.log(triangle("RBRGBRB"))
// console.log(triangle("RBRGBRBGGRRRBGBBBGG"))
// console.log(triangle("B"))
